### PR TITLE
Improve code intelligence facilities and provide other minor fixes and improvements

### PR DESCRIPTION
**Pull request by adiachenko**
## Overview

This PR offers the following improvements:
- Fixes invalid class references due to missing use statements (namely some exceptions in try-catch blocks and Symfony Console's `InputArgument`)
- Adds or fixes phpdoc comments and object type hints for **significantly improved code intelligence** in PhpStorm. Getting these right was the main motive behind this PR
- Fixes version constraints in `composer.json` because the currently installed packages are incompatible with one another and targeted version of PHP. Also replaces tab indentation with spaces in `composer.json`.

### CODE REVIEW

**Comment by KinaneD** [comment]
Hi @adiachenko, thanks for your first contribution. Helpful indeed, but i do not think we should drop support for php 7.0 and fix Laravel component to 5.7.*. Bowler supports `Illuminate\Foundation\Testing\PendingCommand` but does not rely on it.

**Comment by adiachenko** [comment]
@KinaneD sure, but then I would need to lock the dependencies as follows in order to support older PHP version:

- `"illuminate/console": "5.5.*"`
- `"illuminate/support": "5.5.*"`
- `"illuminate/filesystem: "5.5.*"`
- `"orchestra/testbench": "3.5.*"`

Else CI would fail, as shown here (note that this build was run without changes to composer.lock file): https://travis-ci.org/Vinelab/bowler/jobs/510404763

**Comment by KinaneD** [comment]
Bowler dropped support for Laravel 5.3 in its 0.4.4 Release, it should support Laravel 5.4. While it require php 7.0 or greater.

**Comment by adiachenko** [comment]
@KinaneD I updated the PR to target PHP >= 7.0 and Laravel 5.4 and above.

**Pull request merged**
